name: HTTPZ E2E Tests

on:
  workflow_dispatch:
    inputs:
      core_version:
        description: "KMS Core Version"
        required: false
        default: "v0.11.0-rc7"
        type: string
      connector_version:
        description: "Connector Version"
        required: false
        default: "v0.11.0-rc7.1"
        type: string
      coprocessor_version:
        description: "Coprocessor Image Version"
        required: false
        default: "cc1710f"
        type: string
      db_migration_version:
        description: "Coprocessor DB Migration Image Version"
        required: false
        default: "v0.7.0-rc4"
        type: string
      gateway_version:
        description: "Gateway Image Version"
        required: false
        default: "v0.1.0-rc9"
        type: string
      host_version:
        description: "Host Image Version"
        required: false
        default: "v0.7.0-rc4"
        type: string
      relayer_version:
        description: "Relayer Image Version"
        required: false
        default: "dc02dc0"
        type: string
      tests_version:
        description: "E2E Tests Image Version"
        required: false
        default: "dc02dc0"
        type: string
  pull_request:
    paths:
      - ".github/workflows/httpz-e2e-tests.yml"
      - "httpz/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  httpz-e2e-test:
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"

    runs-on: large_ubuntu_32
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Docker
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_READ_TOKEN }}

      - name: Deploy HTTPZ Stack
        working-directory: httpz
        env:
          CORE_VERSION: ${{ inputs.core_version }}
          CONNECTOR_VERSION: ${{ inputs.connector_version }}
          COPROCESSOR_VERSION: ${{ inputs.coprocessor_version }}
          DB_MIGRATION_VERSION: ${{ inputs.db_migration_version }}
          GATEWAY_VERSION: ${{ inputs.gateway_version }}
          HOST_VERSION: ${{ inputs.host_version }}
          RELAYER_VERSION: ${{ inputs.relayer_version }}
          TESTS_VERSION: ${{ inputs.tests_version }}
        run: |
          ./httpz-cli deploy

      - name: Input proof test
        working-directory: httpz
        run: |
          ./httpz-cli test input-proof

      - name: User Decryption test
        working-directory: httpz
        run: |
          ./httpz-cli test user-decryption

      - name: Public Decryption test (euint64)
        working-directory: httpz
        run: |
          ./httpz-cli test public-decryption

      - name: Public Decryption test (ebytes256)
        working-directory: httpz
        run: |
          ./httpz-cli test public-decryption-ebytes256

      - name: ERC20 test
        working-directory: httpz
        continue-on-error: true
        run: |
          ./httpz-cli test erc20 || true
          echo "IMPORTANT: DO NOT consider this test - ERC20 test needs to be fixed in CI"

      - name: Show logs on test failure
        working-directory: httpz
        if: always()
        run: |
          echo "::group::Relayer Logs"
          ./httpz-cli logs relayer
          echo "::endgroup::"
          echo "::group::Transaction Sender Logs (filtered)"
          ./httpz-cli logs transaction-sender | grep -v "Selected 0 rows to process"
          echo "::endgroup::"

      - name: Cleanup
        working-directory: httpz
        if: always()
        run: |
          ./httpz-cli clean
